package com.gawdscape.launcher;

/**
 *
 * @author Vinnie
 */
public class JavaSettingsDialog extends javax.swing.JDialog {

	/**
	 * Creates new form JavaSettingsDialog
	 *
	 * @param parent
	 * @param modal
	 */
	public JavaSettingsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setLocationRelativeTo(parent);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javaPanel = new com.gawdscape.launcher.ui.DirtPanel();
        titleLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        executableCheckBox = new com.gawdscape.launcher.ui.TransparentCheckBox();
        executableTextField = new javax.swing.JTextField();
        argumentsLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        argumentsTextField = new javax.swing.JTextField();
        closeButton = new com.gawdscape.launcher.ui.TransparentButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Java Settings");

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Java Settings");
        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        executableCheckBox.setSelected(GawdScapeLauncher.config.getCustomJava());
        executableCheckBox.setText("Executable:");
        executableCheckBox.setToolTipText("Use custom Java executable?");
        executableCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executableCheckBoxActionPerformed(evt);
            }
        });

        executableTextField.setText(GawdScapeLauncher.config.getJavaPath());
        executableTextField.setToolTipText("Java Executable File");
        executableTextField.setEnabled(GawdScapeLauncher.config.getCustomJava());

        argumentsLabel.setText("Arguments:");

        argumentsTextField.setText(GawdScapeLauncher.config.getJavaArgs());
        argumentsTextField.setToolTipText("Java VM Arguments");

        closeButton.setText("Close");
        closeButton.setToolTipText("Changes are saved with other settings.");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout javaPanelLayout = new javax.swing.GroupLayout(javaPanel);
        javaPanel.setLayout(javaPanelLayout);
        javaPanelLayout.setHorizontalGroup(
            javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javaPanelLayout.createSequentialGroup()
                        .addGroup(javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(executableCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(argumentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(executableTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .addComponent(argumentsTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, javaPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        javaPanelLayout.setVerticalGroup(
            javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(executableCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(executableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(javaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(argumentsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(argumentsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(javaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		GawdScapeLauncher.config.setJava(executableCheckBox.isSelected(), executableTextField.getText(), argumentsTextField.getText());
		dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void executableCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executableCheckBoxActionPerformed
		executableTextField.setEnabled(executableCheckBox.isSelected());
    }//GEN-LAST:event_executableCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gawdscape.launcher.ui.TransparentLabel argumentsLabel;
    private javax.swing.JTextField argumentsTextField;
    private com.gawdscape.launcher.ui.TransparentButton closeButton;
    private com.gawdscape.launcher.ui.TransparentCheckBox executableCheckBox;
    private javax.swing.JTextField executableTextField;
    private com.gawdscape.launcher.ui.DirtPanel javaPanel;
    private com.gawdscape.launcher.ui.TransparentLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
