package com.gawdscape.launcher;

import com.gawdscape.launcher.updater.Updater;
import com.gawdscape.launcher.util.ImageUtils;
import com.gawdscape.launcher.util.Log;
import com.gawdscape.launcher.util.OperatingSystem;
import com.gawdscape.launcher.auth.SessionManager;
import com.gawdscape.launcher.util.Constants;
import com.gawdscape.launcher.util.Directories;
import com.gawdscape.launcher.util.FileUtils;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author Vinnie
 */
public class LauncherFrame extends javax.swing.JFrame {

	public static String[] packs = new String[0];
	public static String username = "Guest";
	private final boolean news;

	/**
	 * Creates new form LauncherFrame
	 *
	 * @param news
	 */
	public LauncherFrame(boolean news) {
		this.news = news;
		Log.debug("Initializing launcher frame.");
		initComponents();
		loadPacks();
		setLocationRelativeTo(null);
		loadNews();
	}

	private void loadPacks() {
		int id = 0;
		int total = GawdScapeLauncher.modpacks.getPackCount();
		packs = new String[total];
		for (String pack : GawdScapeLauncher.modpacks.getPacks()) {
			File packLogo = new File(Directories.getLogoPath(pack));
			if (!packLogo.exists()) {
				packLogo.getParentFile().mkdirs();
				FileUtils.downloadFile(GawdScapeLauncher.modpacks.getPackUrl(pack) + "/logo.png", packLogo);
			}
			if (packLogo.exists()) {
				packCombo.addItem(new ImageIcon(packLogo.getPath()));
			} else {
				packCombo.addItem(pack);
			}
			packs[id] = pack;
			id++;
		}

		int defaultPackID = GawdScapeLauncher.config.getDefaultPack();
		if (id >= defaultPackID) {
			packCombo.setSelectedIndex(defaultPackID);
		}
	}

	private void loadNews() {
		if (news) {
			try {
				newsPane.setPage(Constants.LAUNCHER_NEWS);
			} catch (IOException ex) {
				Log.error("Error loading news", ex);
			}
		} else {
			remove(scrollPane);
			setSize(554, 134);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        newsPane = new javax.swing.JEditorPane();
        bottomPanel = new com.gawdscape.launcher.ui.CobblestonePanel();
        profilePanel = new com.gawdscape.launcher.ui.TransparentPanel();
        playButton = new com.gawdscape.launcher.ui.TransparentButton();
        optionsButton = new com.gawdscape.launcher.ui.TransparentButton();
        greetingLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        usernameLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        switchUsersLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        logoutLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        aboutLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        packCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GawdScape Launcher");
        setIconImage(ImageUtils.getFavIcon());
        setName("frame"); // NOI18N

        scrollPane.setBorder(null);

        newsPane.setEditable(false);
        newsPane.setBorder(null);
        newsPane.setContentType("text/html"); // NOI18N
        newsPane.setText("Loading news...");
        newsPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        newsPane.addHyperlinkListener(evt -> newsPaneHyperlinkUpdate(evt));
        scrollPane.setViewportView(newsPane);

        playButton.setText("Play");
        playButton.addActionListener(evt -> playButtonActionPerformed(evt));

        optionsButton.setText("Options");
        optionsButton.addActionListener(evt -> optionsButtonActionPerformed(evt));

        greetingLabel.setText("Welcome back");
        greetingLabel.setFont(greetingLabel.getFont().deriveFont(greetingLabel.getFont().getStyle() | java.awt.Font.BOLD));

        usernameLabel.setText("Guest");
        usernameLabel.setFont(usernameLabel.getFont().deriveFont(usernameLabel.getFont().getStyle() | java.awt.Font.BOLD));
        usernameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameLabelMouseClicked(evt);
            }
        });

        switchUsersLabel.setText("Switch Users");
        switchUsersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchUsersLabelMouseClicked(evt);
            }
        });

        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setText("About");
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(switchUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(optionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(aboutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(packCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(packCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newsPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_newsPaneHyperlinkUpdate
		if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
			try {
				OperatingSystem.openLink(evt.getURL().toURI());
			} catch (URISyntaxException ex) {
				Log.error("Invalid URI", ex);
			}
		}
    }//GEN-LAST:event_newsPaneHyperlinkUpdate

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
		playButton.setEnabled(false);
		int packID = packCombo.getSelectedIndex();
		GawdScapeLauncher.config.setDefaultPack(packID);
		Config.saveConfig(GawdScapeLauncher.config);
		GawdScapeLauncher.updater = new Updater(packs[packID]);
		GawdScapeLauncher.updater.start();
    }//GEN-LAST:event_playButtonActionPerformed

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
		new OptionsDialog(this, true).setVisible(true);
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
		GawdScapeLauncher.session = null;
		SessionManager manager = SessionManager.loadSessions();
		manager.removeSession(username);
		SessionManager.saveSessions(manager);
		dispose();
		GawdScapeLauncher.loginDialog = new LoginDialog(new javax.swing.JFrame(), true, manager);
		GawdScapeLauncher.loginDialog.setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
		AboutDialog about = new AboutDialog(new javax.swing.JFrame(), true);
		about.setVisible(true);
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void usernameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameLabelMouseClicked
		try {
			URI uri = new URI("http://www.gawdscape.com/player/" + username);
			OperatingSystem.openLink(uri);
		} catch (URISyntaxException ex) {
			Log.error("Invalid URI", ex);
		}
    }//GEN-LAST:event_usernameLabelMouseClicked

    private void switchUsersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchUsersLabelMouseClicked
		GawdScapeLauncher.session = null;
		dispose();
		GawdScapeLauncher.loginDialog = new LoginDialog(new javax.swing.JFrame(), true, SessionManager.loadSessions());
		GawdScapeLauncher.loginDialog.setVisible(true);
    }//GEN-LAST:event_switchUsersLabelMouseClicked

	public void setPlayEnabled(boolean on) {
		playButton.setEnabled(on);
	}

	public void setUsername(String name) {
		username = name;
		greetingLabel.setText("Welcome back");
		usernameLabel.setText(username);
	}

	public void setOffline() {
		greetingLabel.setText("Offline Mode");
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gawdscape.launcher.ui.WhiteLinkLabel aboutLabel;
    private com.gawdscape.launcher.ui.CobblestonePanel bottomPanel;
    private com.gawdscape.launcher.ui.TransparentLabel greetingLabel;
    private com.gawdscape.launcher.ui.WhiteLinkLabel logoutLabel;
    private static javax.swing.JEditorPane newsPane;
    private com.gawdscape.launcher.ui.TransparentButton optionsButton;
    public static javax.swing.JComboBox packCombo;
    public static com.gawdscape.launcher.ui.TransparentButton playButton;
    private com.gawdscape.launcher.ui.TransparentPanel profilePanel;
    private javax.swing.JScrollPane scrollPane;
    private com.gawdscape.launcher.ui.WhiteLinkLabel switchUsersLabel;
    private com.gawdscape.launcher.ui.WhiteLinkLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
