package com.gawdscape.launcher.ui;

import com.gawdscape.json.game.Library;
import com.gawdscape.json.game.Minecraft;
import com.gawdscape.json.game.Mod;
import com.gawdscape.json.modpacks.ModPack;
import com.gawdscape.launcher.GawdScapeLauncher;
import com.gawdscape.launcher.util.Constants;
import com.gawdscape.launcher.util.Directories;
import com.gawdscape.launcher.util.ImageUtils;
import com.gawdscape.launcher.util.JsonUtils;
import com.gawdscape.launcher.util.OperatingSystem;
import com.google.gson.JsonSyntaxException;

import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;

/**
 *
 * @author Vinnie
 */
public final class AboutDialog extends javax.swing.JDialog {

    private final String packName;

    /**
     * Creates new form AboutDialog
     *
     * @param parent
     */
    public AboutDialog(Frame parent) {
	super(parent, true);
	packName = GawdScapeLauncher.launcherFrame.getSelectedPack();
	initComponents();
	loadModPackData();
    }

    private void loadModPackData() {
	File jsonFile = new File(Directories.getPackDataPath(), packName + ".json");
	if (jsonFile.exists()) {
	    try {
		String localJson = JsonUtils.readJsonFromFile(jsonFile);
		ModPack modpack = JsonUtils.getGson().fromJson(localJson, ModPack.class);
		pack.setText(packName);
		packVersion.setText(modpack.getVersion());
		txtModVersion.setText(modpack.getTexperienceVersion());
		listLibraries(modpack.getLibraries());
		listMods(modpack.getMods());
		loadMinecraftData(modpack.getMinecraftVersion());
		listUserMods(modpack.getId());
	    } catch (IOException | JsonSyntaxException ex) {
		GawdScapeLauncher.LOGGER.log(Level.SEVERE, "Error", ex);
	    }
	}
    }

    private void listLibraries(List<Library> libs) {
	if (libs == null) {
	    packLibraries.setText("No libraries.");
            return;
	}
        libs.stream().forEach((lib) -> {
            packLibraries.append(lib.getArtifactFilename(null)+ "\n");
        });
    }

    private void listMods(List<Mod> mods) {
	if (mods == null) {
	    packMods.setText("No mods.");
            return;
	}
        mods.stream().forEach((mod) -> {
            packMods.append(mod.getArtifactFilename(null)+ "\n");
        });
    }

    private void loadMinecraftData(String version) {
	File minecraftJsonFile = new File(Directories.getMcJson(version));
	if (minecraftJsonFile.exists()) {
	    try {
		String localJson = JsonUtils.readJsonFromFile(minecraftJsonFile);
		Minecraft minecraft = JsonUtils.getGson().fromJson(localJson, Minecraft.class);
		mcVersion.setText(minecraft.getId());
	    } catch (IOException | JsonSyntaxException ex) {
		mcVersion.setText(ex.getMessage());
	    }
	}
    }

    private void listUserMods(String name) {
	File modDir = new File(GawdScapeLauncher.config.getGameDir(name), "bin");
	if (!modDir.exists()) {
	    userMods.setText("No mods directory.");
	    return;
	}
        for (String mod : modDir.list())
            userMods.append(mod + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com.gawdscape.launcher.ui.components.DirtPanel aboutPanel = new com.gawdscape.launcher.ui.components.DirtPanel();
        javax.swing.JLabel gawdscapeImg = new javax.swing.JLabel();
        javax.swing.JLabel launcherImg = new javax.swing.JLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel description1 = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentButton closeButton = new com.gawdscape.launcher.ui.components.TransparentButton();
        com.gawdscape.launcher.ui.components.TransparentLabel copyright = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel versionLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel version = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel directoryLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.WhiteLinkLabel directory = new com.gawdscape.launcher.ui.components.WhiteLinkLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel packLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        pack = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel mcVersionLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        mcVersion = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel gameDirLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.WhiteLinkLabel gameDir = new com.gawdscape.launcher.ui.components.WhiteLinkLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel javaVersionLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel javaVersion = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.HyperLinkLabel forumsLink = new com.gawdscape.launcher.ui.components.HyperLinkLabel();
        com.gawdscape.launcher.ui.components.HyperLinkLabel githubLink = new com.gawdscape.launcher.ui.components.HyperLinkLabel();
        com.gawdscape.launcher.ui.components.HyperLinkLabel wikiLink = new com.gawdscape.launcher.ui.components.HyperLinkLabel();
        com.gawdscape.launcher.ui.components.HyperLinkLabel issuesLink = new com.gawdscape.launcher.ui.components.HyperLinkLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel architectureLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel architecture = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel packVersionLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel packLibrariesLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel packModsLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel txtModLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        com.gawdscape.launcher.ui.components.TransparentLabel userModLabel = new com.gawdscape.launcher.ui.components.TransparentLabel();
        packVersion = new com.gawdscape.launcher.ui.components.TransparentLabel();
        txtModVersion = new com.gawdscape.launcher.ui.components.TransparentLabel();
        javax.swing.JScrollPane packModsScrollPane = new javax.swing.JScrollPane();
        packMods = new javax.swing.JTextArea();
        javax.swing.JScrollPane packLibsScrollPane = new javax.swing.JScrollPane();
        packLibraries = new javax.swing.JTextArea();
        javax.swing.JScrollPane userModsScrollPane = new javax.swing.JScrollPane();
        userMods = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About GawdScape Launcher");
        setIconImage(ImageUtils.getFavIcon());

        gawdscapeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gawdscape/launcher/images/gawdscape.png"))); // NOI18N

        launcherImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gawdscape/launcher/images/launcher.png"))); // NOI18N

        description1.setText("The better Minecraft launcher...");
        description1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        copyright.setText("GawdScapeLauncher  Copyright (C) "+Constants.THIS_YEAR+"  GawdScape");

        versionLabel.setText("Launcher Version:");

        version.setText(String.valueOf(Constants.VERSION));

        directoryLabel.setText("Launcher Directory:");

        directory.setText(Directories.getWorkingDirectory().toString());
        directory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directoryMouseClicked(evt);
            }
        });

        packLabel.setText("Mod Pack:");

        pack.setText("Not Installed");

        mcVersionLabel.setText("Minecraft Version:");

        mcVersion.setText("Not Installed");

        gameDirLabel.setText("Game Directory:");

        gameDir.setText(GawdScapeLauncher.config.getGameDir());
        gameDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameDirMouseClicked(evt);
            }
        });

        javaVersionLabel.setText("Java Version:");

        javaVersion.setText(System.getProperty("java.version"));

        forumsLink.setText("Website");
        forumsLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forumsLinkMouseClicked(evt);
            }
        });

        githubLink.setText("GitHub");
        githubLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                githubLinkMouseClicked(evt);
            }
        });

        wikiLink.setText("Wiki");
        wikiLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wikiLinkMouseClicked(evt);
            }
        });

        issuesLink.setText("Issues");
        issuesLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuesLinkMouseClicked(evt);
            }
        });

        architectureLabel.setText("System Architecture:");

        architecture.setText(System.getProperty("os.arch"));
        architecture.setToolTipText("Does this appear incorrect?\nIf so, you may want to install a 64-bit version of Java.");

        packVersionLabel.setText("Mod Pack Version:");

        packLibrariesLabel.setText("Mod Pack Libraries:");

        packModsLabel.setText("Mod Pack Mods:");

        txtModLabel.setText("Texperience Version:");

        userModLabel.setText("Your Mods:");

        packVersion.setText("Not Installed");

        txtModVersion.setText("Not Installed");

        packMods.setEditable(false);
        packMods.setColumns(20);
        packMods.setRows(2);
        packModsScrollPane.setViewportView(packMods);

        packLibraries.setEditable(false);
        packLibraries.setColumns(20);
        packLibraries.setRows(2);
        packLibsScrollPane.setViewportView(packLibraries);

        userMods.setEditable(false);
        userMods.setColumns(20);
        userMods.setRows(2);
        userModsScrollPane.setViewportView(userMods);

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutPanelLayout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(packVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(aboutPanelLayout.createSequentialGroup()
                                    .addComponent(forumsLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(githubLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(wikiLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(issuesLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(javaVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gameDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(description1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(directoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(packLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mcVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(userModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(aboutPanelLayout.createSequentialGroup()
                                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packModsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packLibrariesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(architectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(architecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packLibsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packModsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userModsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gameDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(javaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mcVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(packVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(directory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(aboutPanelLayout.createSequentialGroup()
                                .addComponent(gawdscapeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(launcherImg)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(launcherImg)
                    .addComponent(gawdscapeImg))
                .addGap(18, 18, 18)
                .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mcVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(packLibrariesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packLibsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(packModsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packModsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userModsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(architectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(architecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forumsLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(githubLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wikiLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuesLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuesLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuesLinkMouseClicked
        OperatingSystem.openLink(Constants.LAUNCHER_ISSUE_LINK);
    }//GEN-LAST:event_issuesLinkMouseClicked

    private void wikiLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wikiLinkMouseClicked
        OperatingSystem.openLink(Constants.LAUNCHER_WIKI_LINK);
    }//GEN-LAST:event_wikiLinkMouseClicked

    private void githubLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubLinkMouseClicked
        OperatingSystem.openLink(Constants.GS_GITHUB_LINK);
    }//GEN-LAST:event_githubLinkMouseClicked

    private void forumsLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forumsLinkMouseClicked
        OperatingSystem.openLink(Constants.GS_FORUM_LINK);
    }//GEN-LAST:event_forumsLinkMouseClicked

    private void gameDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameDirMouseClicked
        OperatingSystem.openFolder(GawdScapeLauncher.config.getGameDirectory());
    }//GEN-LAST:event_gameDirMouseClicked

    private void directoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directoryMouseClicked
        OperatingSystem.openFolder(Directories.getWorkingDirectory());
    }//GEN-LAST:event_directoryMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gawdscape.launcher.ui.components.TransparentLabel mcVersion;
    private com.gawdscape.launcher.ui.components.TransparentLabel pack;
    private javax.swing.JTextArea packLibraries;
    private javax.swing.JTextArea packMods;
    private com.gawdscape.launcher.ui.components.TransparentLabel packVersion;
    private com.gawdscape.launcher.ui.components.TransparentLabel txtModVersion;
    private javax.swing.JTextArea userMods;
    // End of variables declaration//GEN-END:variables
}
