package com.gawdscape.launcher;

import com.gawdscape.json.game.Library;
import com.gawdscape.json.modpacks.ModPack;
import com.gawdscape.json.game.Minecraft;
import com.gawdscape.json.game.Mod;
import com.gawdscape.launcher.util.Constants;
import com.gawdscape.launcher.util.Directories;
import com.gawdscape.launcher.util.ImageUtils;
import com.gawdscape.launcher.util.JsonUtils;
import com.gawdscape.launcher.util.Log;
import com.gawdscape.launcher.util.OperatingSystem;
import com.google.gson.JsonSyntaxException;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author Vinnie
 */
public final class AboutDialog extends javax.swing.JDialog {

	public static String packName;

	/**
	 * Creates new form AboutDialog
	 * @param parent
	 * @param modal
	 */
	public AboutDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		getSelectedModPack();
		initComponents();
		setLocationRelativeTo(parent);
		loadModPackData();
	}

	public void getSelectedModPack() {
		packName = LauncherFrame.packs[LauncherFrame.packCombo.getSelectedIndex()];
	}

	public void loadModPackData() {
		File jsonFile = new File(Directories.getPackDataPath(), packName + ".json");
		if (jsonFile.exists()) {
			try {
				String localJson = JsonUtils.readJsonFromFile(jsonFile);
				ModPack modpack = JsonUtils.getGson().fromJson(localJson, ModPack.class);
				pack.setText(packName);
				packVersion.setText(modpack.getVersion());
				gmVersion.setText(modpack.getGawdModVersion());
				packLibraries.setText(listLibraries(modpack.getLibraries()));
				packMods.setText(listMods(modpack.getMods()));
				loadMinecraftData(modpack.getMinecraftVersion());
				loadMods(modpack.getId());
			} catch (IOException | JsonSyntaxException ex) {
				Log.error("Error", ex);
			}
		}
	}

	public String listLibraries(List<Library> libs) {
		if (libs == null)
			return "[]";
		ArrayList<String> output = new ArrayList();
		libs.stream().forEach((lib) -> {
			output.add(lib.getName());
		});
		return output.toString();
	}

	public String listMods(List<Mod> mods) {
		if (mods == null)
			return "[]";
		ArrayList<String> output = new ArrayList();
		mods.stream().forEach((mod) -> {
			output.add(mod.getName());
		});
		return output.toString();
	}

	public void loadMinecraftData(String version) {
		File minecraftJsonFile = new File(Directories.getMcJson(version));
		if (minecraftJsonFile.exists()) {
			try {
				String localJson = JsonUtils.readJsonFromFile(minecraftJsonFile);
				Minecraft minecraft = JsonUtils.getGson().fromJson(localJson, Minecraft.class);
				mcVersion.setText(minecraft.getId());
			} catch (IOException | JsonSyntaxException ex) {
				mcVersion.setText(ex.getMessage());
			}
		}
	}

	public void loadMods(String name) {
		File modDir = new File(GawdScapeLauncher.config.getGameDir(name), "bin");
		if (!modDir.exists()) {
			userMods.setText("No mods directory.");
			return;
		}
		String[] mods = modDir.list();
		userMods.setText(Arrays.toString(mods));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutPanel = new com.gawdscape.launcher.ui.DirtPanel();
        gawdscapeImg = new javax.swing.JLabel();
        launcherImg = new javax.swing.JLabel();
        description1 = new com.gawdscape.launcher.ui.TransparentLabel();
        description2 = new com.gawdscape.launcher.ui.TransparentLabel();
        closeButton = new com.gawdscape.launcher.ui.TransparentButton();
        copyright = new com.gawdscape.launcher.ui.TransparentLabel();
        versionLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        version = new com.gawdscape.launcher.ui.TransparentLabel();
        directoryLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        directory = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        packLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        pack = new com.gawdscape.launcher.ui.TransparentLabel();
        mcVersionLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        mcVersion = new com.gawdscape.launcher.ui.TransparentLabel();
        gameDirLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        gameDir = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        javaVersionLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        javaVersion = new com.gawdscape.launcher.ui.TransparentLabel();
        forumsLink = new com.gawdscape.launcher.ui.HyperLinkLabel();
        githubLink = new com.gawdscape.launcher.ui.HyperLinkLabel();
        wikiLink = new com.gawdscape.launcher.ui.HyperLinkLabel();
        issuesLink = new com.gawdscape.launcher.ui.HyperLinkLabel();
        architectureLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        architecture = new com.gawdscape.launcher.ui.TransparentLabel();
        packVersionLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        packLibrariesLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        packModsLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        gmLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        userModLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        packVersion = new com.gawdscape.launcher.ui.TransparentLabel();
        packLibraries = new com.gawdscape.launcher.ui.TransparentLabel();
        packMods = new com.gawdscape.launcher.ui.TransparentLabel();
        gmVersion = new com.gawdscape.launcher.ui.TransparentLabel();
        userMods = new com.gawdscape.launcher.ui.TransparentLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About GawdScape Launcher");
        setIconImage(ImageUtils.getFavIcon());

        gawdscapeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gawdscape/launcher/images/gawdscape.png"))); // NOI18N

        launcherImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gawdscape/launcher/images/launcher.png"))); // NOI18N

        description1.setText("The better Minecraft launcher...");
        description1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        description2.setText("Also downloads GawdScape mod packs.");
        description2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        copyright.setText("GawdScapeLauncher  Copyright (C) "+Constants.THIS_YEAR+"  GawdScape");

        versionLabel.setText("Launcher Version:");

        version.setText(String.valueOf(Constants.VERSION));

        directoryLabel.setText("Launcher Directory:");

        directory.setText(Directories.getWorkingDirectory().toString());
        directory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directoryMouseClicked(evt);
            }
        });

        packLabel.setText("Mod Pack:");

        pack.setText("Not Installed");

        mcVersionLabel.setText("Minecraft Version:");

        mcVersion.setText("Not Installed");

        gameDirLabel.setText("Game Directory:");

        gameDir.setText(GawdScapeLauncher.config.getGameDir());
        gameDir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gameDirMouseClicked(evt);
            }
        });

        javaVersionLabel.setText("Java Version:");

        javaVersion.setText(System.getProperty("java.version"));

        forumsLink.setText("Website");
        forumsLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forumsLinkMouseClicked(evt);
            }
        });

        githubLink.setText("GitHub");
        githubLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                githubLinkMouseClicked(evt);
            }
        });

        wikiLink.setText("Wiki");
        wikiLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wikiLinkMouseClicked(evt);
            }
        });

        issuesLink.setText("Issues");
        issuesLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuesLinkMouseClicked(evt);
            }
        });

        architectureLabel.setText("System Architecture:");

        architecture.setText(System.getProperty("os.arch"));
        architecture.setToolTipText("Does this appear incorrect?\nIf so, you may want to install a 64-bit version of Java.");

        packVersionLabel.setText("Mod Pack Version:");

        packLibrariesLabel.setText("Mod Pack Libraries:");

        packModsLabel.setText("Mod Pack Mods:");

        gmLabel.setText("GawdMod Version:");

        userModLabel.setText("Your Mods:");

        packVersion.setText("Not Installed");

        packLibraries.setText("N/A");

        packMods.setText("N/A");

        gmVersion.setText("Not Installed");

        userMods.setText("None");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(userModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userMods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(packLibrariesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(packLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(packVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(packVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(forumsLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(githubLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(wikiLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(issuesLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(javaVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(javaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(gameDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(gameDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(mcVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(mcVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(packLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(directoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(directory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(aboutPanelLayout.createSequentialGroup()
                            .addComponent(gawdscapeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(launcherImg))
                        .addComponent(description1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(description2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(architectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(architecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(gmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gmVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutPanelLayout.createSequentialGroup()
                        .addComponent(packModsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(packMods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(launcherImg)
                    .addComponent(gawdscapeImg))
                .addGap(20, 20, 20)
                .addComponent(description1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(version, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packLibrariesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packLibraries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packModsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(packMods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gmVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mcVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mcVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userModLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userMods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameDirLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gameDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(architectureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(architecture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(forumsLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(githubLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wikiLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuesLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(aboutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void issuesLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuesLinkMouseClicked
        OperatingSystem.openLink(Constants.LAUNCHER_ISSUE_LINK);
    }//GEN-LAST:event_issuesLinkMouseClicked

    private void wikiLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wikiLinkMouseClicked
        OperatingSystem.openLink(Constants.LAUNCHER_WIKI_LINK);
    }//GEN-LAST:event_wikiLinkMouseClicked

    private void githubLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_githubLinkMouseClicked
        OperatingSystem.openLink(Constants.GS_GITHUB_LINK);
    }//GEN-LAST:event_githubLinkMouseClicked

    private void forumsLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forumsLinkMouseClicked
        OperatingSystem.openLink(Constants.GS_FORUM_LINK);
    }//GEN-LAST:event_forumsLinkMouseClicked

    private void gameDirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gameDirMouseClicked
        OperatingSystem.openFolder(GawdScapeLauncher.config.getGameDirectory());
    }//GEN-LAST:event_gameDirMouseClicked

    private void directoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directoryMouseClicked
        OperatingSystem.openFolder(Directories.getWorkingDirectory());
    }//GEN-LAST:event_directoryMouseClicked

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gawdscape.launcher.ui.DirtPanel aboutPanel;
    private com.gawdscape.launcher.ui.TransparentLabel architecture;
    private com.gawdscape.launcher.ui.TransparentLabel architectureLabel;
    private com.gawdscape.launcher.ui.TransparentButton closeButton;
    private com.gawdscape.launcher.ui.TransparentLabel copyright;
    private com.gawdscape.launcher.ui.TransparentLabel description1;
    private com.gawdscape.launcher.ui.TransparentLabel description2;
    private com.gawdscape.launcher.ui.WhiteLinkLabel directory;
    private com.gawdscape.launcher.ui.TransparentLabel directoryLabel;
    private com.gawdscape.launcher.ui.HyperLinkLabel forumsLink;
    private com.gawdscape.launcher.ui.WhiteLinkLabel gameDir;
    private com.gawdscape.launcher.ui.TransparentLabel gameDirLabel;
    private javax.swing.JLabel gawdscapeImg;
    private com.gawdscape.launcher.ui.HyperLinkLabel githubLink;
    private com.gawdscape.launcher.ui.TransparentLabel gmLabel;
    private com.gawdscape.launcher.ui.TransparentLabel gmVersion;
    private com.gawdscape.launcher.ui.HyperLinkLabel issuesLink;
    private com.gawdscape.launcher.ui.TransparentLabel javaVersion;
    private com.gawdscape.launcher.ui.TransparentLabel javaVersionLabel;
    private javax.swing.JLabel launcherImg;
    private com.gawdscape.launcher.ui.TransparentLabel mcVersion;
    private com.gawdscape.launcher.ui.TransparentLabel mcVersionLabel;
    private com.gawdscape.launcher.ui.TransparentLabel pack;
    private com.gawdscape.launcher.ui.TransparentLabel packLabel;
    private com.gawdscape.launcher.ui.TransparentLabel packLibraries;
    private com.gawdscape.launcher.ui.TransparentLabel packLibrariesLabel;
    private com.gawdscape.launcher.ui.TransparentLabel packMods;
    private com.gawdscape.launcher.ui.TransparentLabel packModsLabel;
    private com.gawdscape.launcher.ui.TransparentLabel packVersion;
    private com.gawdscape.launcher.ui.TransparentLabel packVersionLabel;
    private com.gawdscape.launcher.ui.TransparentLabel userModLabel;
    private com.gawdscape.launcher.ui.TransparentLabel userMods;
    private com.gawdscape.launcher.ui.TransparentLabel version;
    private com.gawdscape.launcher.ui.TransparentLabel versionLabel;
    private com.gawdscape.launcher.ui.HyperLinkLabel wikiLink;
    // End of variables declaration//GEN-END:variables
}
