package com.gawdscape.launcher;

import com.gawdscape.launcher.download.Updater;
import com.gawdscape.launcher.util.ImageUtils;
import com.gawdscape.launcher.util.Log;
import com.gawdscape.launcher.util.OperatingSystem;
import com.gawdscape.launcher.auth.SessionManager;
import com.gawdscape.launcher.util.Constants;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author Vinnie
 */
public class LauncherFrame extends javax.swing.JFrame {

    public static String username = "Guest";

    /**
     * Creates new form LauncherFrame
     */
    public LauncherFrame() {
	Log.debug("Initializing launcher frame.");
	initComponents();
	setLocationRelativeTo(null);
	loadNews();
    }

    private void loadNews() {
	if (GawdScapeLauncher.config.getShowNews()) {
	    try {
		newsPane.setPage(Constants.LAUNCHER_NEWS);
	    } catch (IOException ex) {
		Log.error("Error loading news", ex);
	    }
	} else {
	    remove(scrollPane);
	    setSize(554, 134);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        newsPane = new javax.swing.JEditorPane();
        bottomPanel = new com.gawdscape.launcher.ui.CobblestonePanel();
        profilePanel = new com.gawdscape.launcher.ui.TransparentPanel();
        playButton = new com.gawdscape.launcher.ui.TransparentButton();
        optionsButton = new com.gawdscape.launcher.ui.TransparentButton();
        greetingLabel = new com.gawdscape.launcher.ui.TransparentLabel();
        usernameLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        switchUsersLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        logoutLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        aboutLabel = new com.gawdscape.launcher.ui.WhiteLinkLabel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GawdScape Launcher");
        setIconImage(ImageUtils.getFavIcon());
        setName("frame"); // NOI18N

        scrollPane.setBorder(null);

        newsPane.setEditable(false);
        newsPane.setBorder(null);
        newsPane.setContentType("text/html"); // NOI18N
        newsPane.setText("Loading news...");
        newsPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        newsPane.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {
                newsPaneHyperlinkUpdate(evt);
            }
        });
        scrollPane.setViewportView(newsPane);

        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        optionsButton.setText("Options");
        optionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsButtonActionPerformed(evt);
            }
        });

        greetingLabel.setText("Welcome back");
        greetingLabel.setFont(greetingLabel.getFont().deriveFont(greetingLabel.getFont().getStyle() | java.awt.Font.BOLD));

        usernameLabel.setText("Guest");
        usernameLabel.setFont(usernameLabel.getFont().deriveFont(usernameLabel.getFont().getStyle() | java.awt.Font.BOLD));
        usernameLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameLabelMouseClicked(evt);
            }
        });

        switchUsersLabel.setText("Switch Users");
        switchUsersLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchUsersLabelMouseClicked(evt);
            }
        });

        logoutLabel.setText("Logout");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        aboutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLabel.setText("About");
        aboutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(switchUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, profilePanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(optionsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(playButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(aboutLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchUsersLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gawdscape/launcher/images/gawdscape.png"))); // NOI18N

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newsPaneHyperlinkUpdate(javax.swing.event.HyperlinkEvent evt) {//GEN-FIRST:event_newsPaneHyperlinkUpdate
	if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            try {
                OperatingSystem.openLink(evt.getURL().toURI());
            } catch (URISyntaxException ex) {
                Log.error("Invalid URI", ex);
            }
	}
    }//GEN-LAST:event_newsPaneHyperlinkUpdate

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
	playButton.setEnabled(false);
	Config.saveConfig(GawdScapeLauncher.config);
	GawdScapeLauncher.updater = new Updater();
	GawdScapeLauncher.updater.start();
    }//GEN-LAST:event_playButtonActionPerformed

    private void optionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionsButtonActionPerformed
	new OptionsDialog(this, true).setVisible(true);
    }//GEN-LAST:event_optionsButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
	GawdScapeLauncher.session = null;
	SessionManager manager = SessionManager.loadSessions();
	manager.removeSession(username);
	SessionManager.saveSessions(manager);
	dispose();
	GawdScapeLauncher.loginDialog = new LoginDialog(new javax.swing.JFrame(), true, manager);
	GawdScapeLauncher.loginDialog.setVisible(true);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void aboutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLabelMouseClicked
        AboutDialog about = new AboutDialog(new javax.swing.JFrame(), true);
        about.setVisible(true);
    }//GEN-LAST:event_aboutLabelMouseClicked

    private void usernameLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameLabelMouseClicked
	try {
	    URI uri = new URI("http://www.gawdscape.com/go/player/" + username);
	    OperatingSystem.openLink(uri);
	} catch (URISyntaxException ex) {
	    Log.error("Invalid URI", ex);
	}
    }//GEN-LAST:event_usernameLabelMouseClicked

    private void switchUsersLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchUsersLabelMouseClicked
	GawdScapeLauncher.session = null;
	dispose();
	GawdScapeLauncher.loginDialog = new LoginDialog(new javax.swing.JFrame(), true, SessionManager.loadSessions());
	GawdScapeLauncher.loginDialog.setVisible(true);
    }//GEN-LAST:event_switchUsersLabelMouseClicked

    public void setUsername(String name) {
	username = name;
	greetingLabel.setText("Welcome back");
	usernameLabel.setText(username);
    }

    public void setOffline(String username) {
	greetingLabel.setText("Offline Mode");
	usernameLabel.setText(username);
	logoutLabel.setText("Retry");
    }

    public void setError(String error) {
	greetingLabel.setText("Login Error:");
	usernameLabel.setText(error);
	logoutLabel.setText("Retry");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the System look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	try {
	    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(LauncherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new LauncherFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gawdscape.launcher.ui.WhiteLinkLabel aboutLabel;
    private com.gawdscape.launcher.ui.CobblestonePanel bottomPanel;
    private com.gawdscape.launcher.ui.TransparentLabel greetingLabel;
    private javax.swing.JLabel logoLabel;
    private com.gawdscape.launcher.ui.WhiteLinkLabel logoutLabel;
    private static javax.swing.JEditorPane newsPane;
    private com.gawdscape.launcher.ui.TransparentButton optionsButton;
    public static com.gawdscape.launcher.ui.TransparentButton playButton;
    private com.gawdscape.launcher.ui.TransparentPanel profilePanel;
    private javax.swing.JScrollPane scrollPane;
    private com.gawdscape.launcher.ui.WhiteLinkLabel switchUsersLabel;
    private com.gawdscape.launcher.ui.WhiteLinkLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
