package com.gawdscape.launcher;

import com.gawdscape.launcher.util.Constants;
import com.gawdscape.launcher.util.ImageUtils;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Vinnie
 */
public class LogFrame extends javax.swing.JFrame {

    public static StyledDocument log;

    /**
     * Creates new form Console
     */
    public LogFrame() {
	initComponents();
	setLocation(20, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        logPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GawdScape Log");
        setIconImage(ImageUtils.getFavIcon());
        setName("frame"); // NOI18N

        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        logPane.setEditable(false);
        logPane.setBackground(new java.awt.Color(0, 0, 0));
        logPane.setFont(new java.awt.Font("Lucida Console", 1, 11)); // NOI18N
        logPane.setForeground(new java.awt.Color(205, 205, 205));
        logPane.setText("GawdScape Launcher [Version " + Constants.VERSION + "]\n(c) 2014 GawdScape Networks.\n\n");
        logPane.setAutoscrolls(false);
        logPane.setCaretColor(new java.awt.Color(205, 205, 205));
        logPane.setMargin(new java.awt.Insets(0, 0, 0, 0));
        logPane.setPreferredSize(new java.awt.Dimension(661, 304));
        logPane.setSelectedTextColor(new java.awt.Color(63, 63, 63));
        logPane.setSelectionColor(new java.awt.Color(255, 255, 255));
        log = logPane.getStyledDocument();
        scrollPane.setViewportView(logPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the System look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	try {
	    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
	} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(LauncherFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new LogFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextPane logPane;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
